events {}

http {
  upstream web_backend {
    server web1:80 max_fails=1 fail_timeout=5s;
    server web2:80 max_fails=1 fail_timeout=5s;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://web_backend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_next_upstream error timeout http_500 http_502 http_503 http_504;
      add_header X-Load-Balancer "nginx" always;
    }
  }
}
